In [31]:
import numpy as np 

In [33]:
#creating sd formula:
def sd(x):
    num=((x-x.mean())**2).sum()
    deno = x.size-1
    return (num/deno)**0.5

In [34]:
##scaling input feautures and labels for regression models:
def scale(x):
    num=x-x.mean()
    den=sd(x)
    return num/den

In [35]:
##creating scalematrix:
def scalematrix(m):
    for i in range(m.shape[1]):
        col=m[:,:]
        m[:,:]=scale(col)
        return m

In [36]:
f=open("D:\samples_data_DS\samp_16.txt")
head=f.readline()
lines=f.readlines()
print(lines)

['101,"vamshi",23,50,5.9,60\n', '102,"kanny",32,55,5.6,62\n', '103,"sunny",25,60,4.5,70\n', '104,"aero",34,70,5.8,79\n', '105,"funny",26,65,5.9,57\n', '106,"bunny",28,75,6.1,89']


In [38]:
m=[]
for line in lines:
    w=[float(v) for v in line.strip().split(",")[2:]]
    m.append(w)
M=np.array(m)
S=scalematrix(M)
print(S)

[[-0.6680371   0.31179097 -1.28859487  0.67469025]
 [-0.34142774  0.49324061 -1.29948185  0.74727011]
 [-0.59545724  0.67469025 -1.33940077  1.03758953]
 [-0.26884788  1.03758953 -1.29222386  1.36419888]
 [-0.55916731  0.85613989 -1.28859487  0.56582046]
 [-0.48658745  1.21903917 -1.28133688  1.72709817]]


In [44]:
##input matrix:
x=np.ones(M.shape)
x[:,1:]=M[:,:-1]
print(x)

[[ 1.         -0.6680371   0.31179097 -1.28859487]
 [ 1.         -0.34142774  0.49324061 -1.29948185]
 [ 1.         -0.59545724  0.67469025 -1.33940077]
 [ 1.         -0.26884788  1.03758953 -1.29222386]
 [ 1.         -0.55916731  0.85613989 -1.28859487]
 [ 1.         -0.48658745  1.21903917 -1.28133688]]


In [46]:
##output or label matrix:
y=np.c_[M[:,-1]]
print(y)

[[0.67469025]
 [0.74727011]
 [1.03758953]
 [1.36419888]
 [0.56582046]
 [1.72709817]]
